[package]
name = "waterfall-demo"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.1.6", features = ["derive"] }
glow = "0.12.1"
glutin = { version = "0.28" }
num = "0.4.0"
rand = "0.8.5"
rand_distr = "0.4.3"
rustfft = "6.1.0"
